name: d

on:
  workflow_dispatch:

jobs:
  fetch_and_notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run zhenghe.py
        env:
          KR_URL: ${{ secrets.KR_URL }}
          KR_REFERER: ${{ secrets.KR_REFERER }}
          TW_URL: ${{ secrets.TW_URL }}
          TW_REFERER: ${{ secrets.TW_REFERER }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python zhenghe.py

      - name: Send to Discord (if separate)
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL2 }}
        run: python send_to_dis.py

      - name: Trigger Workflow D via GitHub API
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/robot4black/km901/actions/workflows/d.yaml/dispatches \
            -d '{"ref":"main"}'
