name: d

on:
  workflow_dispatch:   

jobs:
  fetch_and_notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ko.py
        env:
          EVENT_ID: ${{ secrets.EVENT_ID }}
          BASE_URL: ${{ secrets.BASE_URL }}
          REFERER_BASE: ${{ secrets.REFERER_BASE }}
        run: python ko.py
        
      - name: Send to Discord
        run: python send_to_dis.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Trigger Workflow D via GitHub API
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/robot4black/km901/actions/workflows/d.yaml/dispatches \
            -d '{"ref":"main"}'
